


spring:
  profiles:
    active: ${PROJECT_PROFILES:dev}


server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: ${SERVER-PATH:/csv-generator}
props:
  generator_path: ${GENERATE_PATH:C:/Users/Maksim_Liashchuk/Desktop/tempDir/}
  generator_row_count: ${GENERATE_ROW_COUNT:500}
  s3url: ${MINIO_URL:http://localhost:9000}
  s3bucket: ${MINIO_BUCKET:file-storage}
  s3accesskey: ${MINIO_ACCESS_KEY:Q3AM3UQ867SPQQA43P2F}
  s3secretkey: ${MINIO_SECRET_KEY:tfteSlswRu7BJ86wekitnifILbZam1KYY3TG}